version: "3"
services:
  sync:
    restart: unless-stopped
    container_name: archiver
    build:
      context: .
      dockerfile: Dockerfile
    command: ['node', 'dispatch.js', 'sync']
    environment:
      - HARDHAT_NETWORK=mainnet